import { Topic, Subject } from './types';

export const SUBJECTS: Subject[] = [
  { id: 'math', name: 'Mathematics', color: '#1F51BA' },
  { id: 'physics', name: 'Physics', color: '#00BCD4' },
  { id: 'chemistry', name: 'Chemistry', color: '#ba1a1a' },
  { id: 'history', name: 'History', color: '#840d1b' },
  { id: 'bio', name: 'Biology', color: '#006876' },
  { id: 'economics', name: 'Economics', color: '#a5292f' },
];

export const MOCK_TOPICS: Topic[] = [
  {
    id: '1',
    subjectId: 'math',
    name: 'Integration',
    description: 'Calculus fundamentals and integration techniques.',
    createdAt: '2026-04-10',
    nextRevisionDate: '2026-04-26',
    status: 'ACTIVE',
    difficulty: 'Hard',
    streak: 3,
    history: [
      { date: '2026-04-11', status: 'COMPLETED' },
      { date: '2026-04-15', status: 'COMPLETED' },
      { date: '2026-04-20', status: 'RESCHEDULED' },
    ],
    attachments: [],
  },
  {
    id: '2',
    subjectId: 'physics',
    name: 'Electrostatics',
    description: 'Static electricity and electric fields.',
    createdAt: '2026-04-05',
    lastRevised: '2026-04-24',
    nextRevisionDate: '2026-04-30',
    status: 'ACTIVE',
    difficulty: 'Medium',
    streak: 5,
    history: [
      { date: '2026-04-10', status: 'COMPLETED' },
      { date: '2026-04-15', status: 'COMPLETED' },
      { date: '2026-04-20', status: 'SKIPPED' },
      { date: '2026-04-24', status: 'COMPLETED' },
    ],
    attachments: [
      { id: 'a1', type: 'NOTE', name: 'Electrostatics Notes.txt' },
      { id: 'a2', type: 'IMAGE', name: "Coulomb's Law Diagram" },
    ],
  },
  {
    id: '3',
    subjectId: 'chemistry',
    name: 'Chemical Bonding',
    description: 'Ionic, covalent and metallic bonding.',
    createdAt: '2026-04-12',
    nextRevisionDate: '2026-04-26',
    status: 'ACTIVE',
    difficulty: 'Medium',
    streak: 1,
    history: [
      { date: '2026-04-13', status: 'COMPLETED' },
    ],
    attachments: [],
  },
  {
    id: '4',
    subjectId: 'physics',
    name: 'Quantum Mechanics',
    createdAt: '2026-04-15',
    nextRevisionDate: '2026-04-28',
    status: 'ACTIVE',
    difficulty: 'Hard',
    streak: 0,
    history: [],
    attachments: [],
  },
  {
    id: '5',
    subjectId: 'chemistry',
    name: 'Organic Synthesis',
    createdAt: '2026-04-18',
    nextRevisionDate: '2026-04-28',
    status: 'ACTIVE',
    difficulty: 'Hard',
    streak: 0,
    history: [],
    attachments: [],
  },
  {
    id: '6',
    subjectId: 'math',
    name: 'Linear Algebra',
    createdAt: '2026-04-20',
    nextRevisionDate: '2026-04-30',
    status: 'ACTIVE',
    difficulty: 'Medium',
    streak: 0,
    history: [],
    attachments: [],
  }
];
